### ISSUE TITLE
custom json font issue ?

### ISSUE THREAD

**Issue by ykvox** [PuckiSilver/NoShadow#3]
hi ! i'd love to use your shader, sadly i'm running into an issue where:
![image](https://github.com/PuckiSilver/NoShadow/assets/61479000/bbfb268c-597c-4e3a-8e9e-9d0c24373762)
(without the drop shadow of course)

but as soon as i'm moving the shader file in my ressourcepack it goes

![image](https://github.com/PuckiSilver/NoShadow/assets/61479000/f32221a4-1686-4ed7-837d-215066752b0a)

do note that i am very very new to all of this so it might be that i made something completely wrong
i'm using a custom json font in the text
thank you in advance ! :)

**Comment by PuckiSilver** [comment]
🤔 It shouldn't be able to do that, you get these boxes if the text can't load the font and this pack only adds a shader and doesn't mess with actual fonts at all

- How does your folder structure look?
- How does the other resource pack achieve the bevel and gradient effect?
- Did you need to replace any files when placing NoShadows files into the other pack?

Also, communication will probably be quicker on discord, since I check it more often, feel free to message request or add `puckisilver` on there

**Comment by ykvox** [comment]
sure ! i added you on discord, i'll send you more detail of how i put this together once you accepted it :)
thanks again !
